# Generated by Django 5.1.7 on 2026-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_tobuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
