# Generated by Django 5.1.7 on 2026-04-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_gym_setting_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(choices=[('salary', 'Staff Salary'), ('equipment', 'Equipment Purchase/Repair'), ('rent', 'Rent & Utilities'), ('to-buy', 'To-Buy Items'), ('supplies', 'Supplies'), ('marketing', 'Marketing'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
