# Generated by Django 4.2.9 on 2026-03-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(blank=True, max_length=15)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('in_app', 'In-App')], default='email', max_length=10)),
                ('trigger_type', models.CharField(choices=[('renewal_remind', 'Renewal Reminder'), ('renewal_confirm', 'Renewal Confirmed'), ('enrollment', 'New Enrollment'), ('expiry', 'Membership Expired'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
