# Generated by Django 5.1.7 on 2026-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient_email',
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
