# Generated by Django 5.1.7 on 2026-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_recipient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='trigger_type',
            field=models.CharField(choices=[('renewal_remind', 'Renewal Reminder'), ('renewal_confirm', 'Renewal Confirmed'), ('enrollment', 'New Enrollment'), ('expiry', 'Membership Expired'), ('manual', 'Manual'), ('enquiry_welcome', 'Enquiry Welcome'), ('enquiry_followup', 'Enquiry Follow-up')], default='manual', max_length=20),
        ),
    ]
