# Generated by Django 5.1.7 on 2026-04-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_trigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger_type',
            field=models.CharField(choices=[('renewal_remind', 'Renewal Reminder'), ('renewal_confirm', 'Renewal Confirmed'), ('enrollment', 'New Enrollment'), ('expiry', 'Membership Expired'), ('manual', 'Manual'), ('enquiry_welcome', 'Enquiry Welcome'), ('enquiry_followup', 'Enquiry Follow-up'), ('absent', 'Member Absent'), ('staff_absent', 'Staff Absent'), ('new_plan', 'New Plan Announcement'), ('diet_reminder', 'Diet Reminder')], default='manual', max_length=20),
        ),
    ]
