# Generated by Django 5.1.7 on 2026-03-26 09:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('working_days_preset', models.CharField(choices=[('mon_sun', 'Mon – Sun (All week)'), ('mon_fri', 'Mon – Fri (Weekdays)'), ('mon_sat', 'Mon – Sat'), ('sat_sun', 'Sat – Sun (Weekends)'), ('custom', 'Custom days')], default='mon_sun', max_length=10)),
                ('working_days', models.CharField(default='0,1,2,3,4,5,6', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('late_grace_minutes', models.PositiveIntegerField(default=15)),
                ('overtime_threshold_minutes', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('trainer', 'Trainer'), ('receptionist', 'Receptionist'), ('cleaner', 'Cleaner'), ('manager', 'Manager'), ('other', 'Other')], default='trainer', max_length=20)),
                ('shift', models.CharField(choices=[('morning', 'Morning 6AM-2PM'), ('evening', 'Evening 2PM-10PM'), ('full', 'Full Day'), ('off', 'Day Off')], default='morning', max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('join_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('photo_url', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.staffshift')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half', 'Half Day'), ('leave', 'Leave'), ('late', 'Late'), ('overtime', 'Overtime'), ('late_overtime', 'Late + Overtime'), ('auto_absent', 'Auto Absent')], default='present', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('worked_minutes', models.IntegerField(default=0)),
                ('late_minutes', models.IntegerField(default=0)),
                ('overtime_minutes', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('staff', 'month')},
            },
        ),
    ]
