# Generated by Django 5.1.7 on 2026-03-25 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffattendance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('working_days_preset', models.CharField(choices=[('mon_sun', 'Mon – Sun (All week)'), ('mon_fri', 'Mon – Fri (Weekdays)'), ('mon_sat', 'Mon – Sat'), ('sat_sun', 'Sat – Sun (Weekends)'), ('custom', 'Custom days')], default='mon_sun', max_length=10)),
                ('working_days', models.CharField(default='0,1,2,3,4,5,6', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('late_grace_minutes', models.PositiveIntegerField(default=15)),
                ('overtime_threshold_minutes', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='worked_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half', 'Half Day'), ('leave', 'Leave'), ('late', 'Late'), ('overtime', 'Overtime'), ('auto_absent', 'Auto Absent')], default='present', max_length=15),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='shift_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.staffshift'),
        ),
    ]
