# Generated by Django 5.1.7 on 2026-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffshift_staffattendance_late_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half', 'Half Day'), ('leave', 'Leave'), ('late', 'Late'), ('overtime', 'Overtime'), ('late_overtime', 'Late + Overtime'), ('auto_absent', 'Auto Absent')], default='present', max_length=15),
        ),
    ]
