# Generated by Django 5.1.7 on 2026-03-19 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='paid_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
