# Generated by Django 5.1.7 on 2026-03-19 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_join_date_alter_memberpayment_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='memberpayment',
            name='amount',
        ),
        migrations.AddField(
            model_name='member',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membershipplan'),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membershipplan'),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('pending', 'Pending')], default='paid', max_length=10),
        ),
    ]
