# Generated by Django 5.1.7 on 2026-03-27 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_trainerassignment'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerassignment',
            options={},
        ),
        migrations.AlterField(
            model_name='trainerassignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AlterField(
            model_name='trainerassignment',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, to='staff.staffmember'),
        ),
    ]
