# Generated by Django 5.1.7 on 2026-03-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_trainerassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='personal_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
