# Generated by Django 5.1.7 on 2026-03-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_memberattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpayment',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='total_with_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
