# Generated by Django 5.1.7 on 2026-03-26 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_diet_dietplan_membershipplan_plans_member_diet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='name',
            field=models.CharField(default='Unnamed Plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.dietplan'),
        ),
    ]
