# Generated by Django 5.1.7 on 2026-03-24 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memberpayment_gst_amount_memberpayment_gst_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('renewal', 'Renewal'), ('balance', 'Balance Payment')], default='balance', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='members.member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='members.memberpayment')),
            ],
            options={
                'ordering': ['paid_date', 'created_at'],
            },
        ),
    ]
