# Generated by Django 5.1.7 on 2026-03-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_membershipplan_plans_member_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='personal_trainer',
        ),
    ]
