# Generated by Django 5.1.7 on 2026-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_dietplan_name_alter_dietplan_id_alter_member_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AddField(
            model_name='diet',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('piece', 'Piece')], default='g', max_length=10),
        ),
    ]
