# Generated by Django 5.1.7 on 2026-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_membershipplan_personal_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='mode_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=10),
        ),
    ]
