# Generated by Django 5.1.7 on 2026-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_diet_quantity_diet_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
