# Generated by Django 5.1.7 on 2026-04-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_installmentpayment_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerassignment',
            name='trainer_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
