# Generated by Django 5.1.7 on 2026-04-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_ptrenewal_trainer_payout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietplan',
            options={'ordering': ['name']},
        ),
    ]
