# Generated by Django 5.1.7 on 2026-04-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_dietplan_options'),
        ('members', '0012_memberpayment_diet_plan_amount'),
    ]

    operations = [
    ]
