# Generated by Django 5.1.7 on 2026-04-13 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_merge_20260410_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joining_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
