# Generated by Django 5.1.7 on 2026-04-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_member_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('dietonly-standard', 'Standard (Diet Only)')], default='basic', max_length=20),
        ),
    ]
