# Generated by Django 5.1.7 on 2026-04-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_member_email'),
        ('members', '0015_alter_member_plan_type'),
    ]

    operations = [
    ]
